version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: customer_admin
      POSTGRES_PASSWORD: 7h>\}aa/XP!<-Km
      POSTGRES_DB: customer_admin
      PORT: 5432
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - '5432:5432'
  
volumes:
  postgres-db:
    driver: local
